## Back-end server configuration playbook goes here.
---
- name: "update apt packages."
  become: true
  apt:
    update_cache: yes

- name: "upgrade packages."
  become: true
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: true
  apt:
    autoremove: yes

- name: "install dependencies."
  become: true
  apt:
    name: ["unzip", "curl", "git"]
    state: latest
    update_cache: yes

- name: Install nvm
  become: true
  shell: |
    curl https://raw.githubusercontent.com/creationix/nvm/master/install.sh | sudo -E bash 

- name: Install node
  become: true
  shell: |
      source ~/.nvm/nvm.sh 
      nvm install 13.8.0
      nvm alias default 13.8.0                               
  args:
      executable: /bin/bash

- name: "install pm2"
  become: true
  npm:
    name: pm2
    global: yes
    production: yes
    state: present